use CJA_UNIVER;

SELECT * FROM FACULTY;
SELECT TEACHER, PULPIT from TEACHER;
SELECT TEACHER_NAME FROM TEACHER where PULPIT='»—Ë“';
SELECT TEACHER_NAME FROM TEACHER where PULPIT='»—Ë“' or PULPIT='œŒË—Œ»';
SELECT TEACHER_NAME FROM TEACHER where GENDER='Ê' and PULPIT='»—Ë“';
SELECT TEACHER_NAME FROM TEACHER where GENDER!='Ê' and PULPIT='»—Ë“';
SELECT Distinct PULPIT from TEACHER;

SELECT Distinct AUDITORIUM, AUDITORIUM_CAPACITY from AUDITORIUM Order by AUDITORIUM_CAPACITY ASC;
SELECT Distinct Top(2) AUDITORIUM_TYPE, AUDITORIUM_CAPACITY from AUDITORIUM Order by AUDITORIUM_CAPACITY ASC;

SELECT Distinct SUBJECT from PROGRESS where NOTE between 8 and 1;

SELECT Distinct SUBJECT from SUBJECT where PULPIT in ('À«Ëƒ¬','œŒË—Œ»','Œ¬');

SELECT PROFESSION_NAME, QUALIFICATION from PROFESSION where QUALIFICATION Like '%ıËÏËÍ%';

--DROP table #H;	
--CREATE table #H
--(	FIO nvarchar(100),
--	DR date
--)
--SELECT NAME, BDAY INTO #H(FIO, DR) from STUDENT;
--SELECT * FROM #H;
--DROP table #H;
